# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/CasaGH
spring.datasource.username=postgres
spring.datasource.password=CasaGH

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# App Name
spring.application.name=casagh-backend

# JWT Settings
jwt.secret=casaghSecretKey2026ThisIsAVeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000

# File Upload Settings
file.upload-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Paystack Settings
paystack.secret.key=sk_test_7e455d0110daf611e48ba41faaebd0ee8d4f0f09